foreground   #e0e1f2
background   #101325
cursor       #e0e1f2

color0       #101325
color8       #9c9da9
color1       #5561D3
color9       #5561D3
color2       #B063E7
color10      #B063E7
color3       #7782BD
color11      #7782BD
color4       #748FE2
color12      #748FE2
color5       #97A4EC
color13      #97A4EC
color6       #BCBFF3
color14      #BCBFF3
color7       #e0e1f2
color15      #e0e1f2
