foreground            #e4e1e9
background            #131318
selection_foreground  #e0e0ff
selection_background  #3d4279
url_color             #bec2ff

color0  #1b1b21
color1  #ffb4ab
color2  #bec2ff
color3  #e7b9d5
color4  #bec2ff
color5  #c5c4dd
color6  #555a92
color7  #e4e1e9
color8  #91909a
color9  #ffb4ab
color10 #bec2ff
color11 #e7b9d5
color12 #bec2ff
color13 #c5c4dd
color14 #555a92
color15 #c7c5d0