foreground   #c1c0bb
background   #06120D
cursor       #c1c0bb

color0       #06120D
color8       #878682
color1       #61655B
color9       #61655B
color2       #6D746C
color10      #6D746C
color3       #8A785C
color11      #8A785C
color4       #7D817A
color12      #7D817A
color5       #98886F
color13      #98886F
color6       #D1A876
color14      #D1A876
color7       #c1c0bb
color15      #c1c0bb
