hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 4,
        border_size = 2,
        col = {
            active_border = { colors = {"rgba(bd93f9ee)", "rgba(ff79c6ee)", "rgba(8be9fdee)"}, angle = 45 },
            inactive_border = { colors = {"rgba(44475a66)"}, angle = 0 }
        },
        layout = "dwindle",
        resize_on_border = true,
        extend_border_grab_area = 15,
    },
    decoration = {
        rounding = 8,
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            new_optimizations = true,
            xray = false,
            ignore_opacity = true,
            popups = true,
            popups_ignorealpha = 0.2,
            noise = 0.02,
            contrast = 1.0,
            brightness = 1.0,
            vibrancy = 0.2,
            vibrancy_darkness = 0.0,
        },
        shadow = {
            enabled = true,
            range = 2,
            render_power = 4,
            color = "rgba(bd93f920)",
            color_inactive = "rgba(00000030)",
        },
        active_opacity = 0.95,
        inactive_opacity = 0.85,
        fullscreen_opacity = 1.0,
        dim_inactive = true,
        dim_strength = 0.08,
        dim_special = 0.3,
    },
    master = {
        new_status = "slave",
        new_on_top = false,
        mfact = 0.55,
        orientation = "left",
        smart_resizing = true,
    },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
        enable_swallow = true,
        swallow_regex = "^(kitty)$",
        focus_on_activate = true,
        middle_click_paste = false,
    },
    cursor = {
        no_hardware_cursors = true,
        hide_on_key_press = true,
        inactive_timeout = 5,
    },
    binds = {
        allow_workspace_cycles = true,
        workspace_back_and_forth = true,
    },
    xwayland = {
        use_nearest_neighbor = false,
        force_zero_scaling = true,
    },
})