# ~/.config/hypr/hyprpaper.conf

# Preload the new wallpaper
preload = /home/saksham/Pictures/wallpaper/wallhaven-6l2rgq_1920x1200.png

# The "Anonymous" set: Leaving the monitor name empty forces it 
# to fill whatever screen it finds first.
wallpaper = , /home/saksham/Pictures/wallpaper/wallhaven-6l2rgq_1920x1200.png

# Essential for the fix
splash = false
ipc = on