-- Hyprland Borders generated by Matugen
return {
    primary = "rgba({{colors.primary.default.hex_stripped}}ff)",
    primaryFixed = "rgba({{colors.primary.default.hex_stripped}}cc)",
    outline = "rgba({{colors.outline.default.hex_stripped}}ff)",
    surface = "rgba({{colors.surface.default.hex_stripped}}ff)"
}